image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

stages:
  - build
  - test
  - deploy
  - container

Build project:
  stage: build
  script:
    - mvn $MAVEN_OPTS compile

Test project:
  stage: test
  script:
    - mvn $MAVEN_OPTS test
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit: target/surefire-reports/TEST-*.xml

Package artifact:
  stage: deploy
  image: bellsoft/liberica-openjdk-alpine:14
  script:
    - chmod +x mvnw
    - ./mvnw $MAVEN_OPTS package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 7 days

Container project:
  stage: container
  image: docker:latest
  services:
    - docker:dind
  script:
    - "cp $(ls target/*.jar) docker/gitlabci.jar"
    - cd docker
    - docker build -t $CI_REGISTRY_IMAGE:my_docker_image
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push $CI_REGISTRY_IMAGE:my_docker_image
