image: maven:latest

variables:
  MAVEN_OPTS: "Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

Build project:
  stage: build
  script:
    - mvn $MAVEN_OPTS compile

Test project:
  stage: test
  script:
    - mvn $MAVEN_OPTS test
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit: target/surefire-reports/TEST-*.xml

Package artifact:
  stage: deploy
  image: bellsoft/liberica-openjdk-alpine:14
  script:
    - ./mvnw $MAVEN_OPTS package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 7 days
